stages:
  - build

# This builds the `latest` tag for the `main` branch
build-latest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE \
        --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg "COMMIT=$CI_COMMIT_SHA" \
        --build-arg "VERSION=$CI_COMMIT_REF_SLUG"
  only:
    - main

# This builds the `branch-<branch-name>` and `branch-<branch-name>-<date>` tags for all branches
build-branch:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG \
        --destination "$CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_SLUG-$(date -u +'%Y%m%d%H%M%S')" \
        --build-arg "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg "COMMIT=$CI_COMMIT_SHA" \
        --build-arg "VERSION=$CI_COMMIT_REF_SLUG"
